version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

executors:
  python-executor:
    docker:
      - image: circleci/python:3.7.4
    working_directory: ~/repo


defaults: &defaults
  executor: python-executor
  working_directory: ~/repo

jobs:
  setup_and_install:
    <<: *defaults
    steps:
      - checkout
      - persist_to_workspace:
          root: .
          paths:
            - .
  linting:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install flake8
            flake8 .

  evaluator_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo

      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install coverage
            sudo pip install --quiet --force-reinstall  --upgrade -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Evaluator tests
          when: always
          command: |
            coverage run -m unittest -v tests/test_deployment.py
            coverage run -m unittest -v tests/test_evaluation.py

      - run:
          name: upload
          when: always
          command: bash <(curl -s https://codecov.io/bash) -cF python

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results-evaluator


  data_quality_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install coverage
            sudo pip install --force-reinstall --upgrade -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Data Quality Tests
          command: |
            coverage run -m unittest -v tests/data_format_tests.py
            coverage run -m unittest -v tests/usgs_tests.py
            coverage run -m unittest -v tests/test_join.py
            coverage run -m unittest -v tests/test_preprocessing.py

      - run:
          name: upload_stuff
          when: always
          command: bash <(curl -s https://codecov.io/bash) -cF python

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results-data-quality


  model_basic_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install coverage
            sudo pip install --force-reinstall --upgrade --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Model basic tests
          when: always
          command: |
            coverage run -m unittest -v tests/time_model_test.py
            coverage run -m unittest -v tests/pytorc_train_tests.py
            python -m unittest -v tests/model_config_tests.py
            python -m unittest -v tests/data_loader_tests.py
            python -m unittest -v tests/test_da_rnn.py

      - run:
          name: upload_stuff
          when: always
          command: bash <(curl -s https://codecov.io/bash) -cF python

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results-model-tests

  decoder_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install coverage
            sudo pip install --upgrade --force-reinstall --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Decoder tests
          when: always
          command: coverage run -m unittest -v tests/test_decoder.py

      - run:
          name: upload_stuff
          when: always
          command: bash <(curl -s https://codecov.io/bash) -cF python

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results-decoder


  trainer_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install --force-reinstall --upgrade --quiet -r requirements.txt
            sudo pip install coverage
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: Trainer tests
          when: always
          command: |
            echo -e 'running da-meta data unit test'
            coverage run flood_forecast/trainer.py -p tests/da_meta.json
            echo -e 'running Deep_AR_test \n'
            coverage run flood_forecast/trainer.py -p tests/DeepAR_test.json
            echo -e 'running transformer bottleneck'
            coverage run flood_forecast/trainer.py -p tests/transformer_bottleneck.json
            echo -e 'running da_rnn probabilistic test'
            coverage run flood_forecast/trainer.py -p tests/da_rnn_probabilistic.json
            echo -e 'running lstm probabilistic test'
            coverage run flood_forecast/trainer.py -p tests/lstm_probabilistic_test.json
            echo -e 'running probabilistic lin reg test'
            coverage run flood_forecast/trainer.py -p tests/probabilistic_linear_regression_test.json
            echo -e 'running meta-data fusion'
            coverage run flood_forecast/trainer.py -p tests/meta_data_test.json
            echo -e 'running da_rnn_test \n'
            coverage run flood_forecast/trainer.py -p tests/da_rnn.json
            echo -e 'running auto test \n'
            coverage run flood_forecast/meta_train.py -p tests/auto_encoder.json
            echo -e 'running trainer_lstm_test \n '
            coverage run flood_forecast/trainer.py -p tests/lstm_test.json
            echo -e 'running trainer_multi_test \n'
            coverage run flood_forecast/trainer.py -p tests/multi_test.json
            echo -e 'running trainer_full_transformer_test \n'
            coverage run flood_forecast/trainer.py -p  tests/full_transformer.json
            echo -e 'running trainer_decoder_test \n'
            coverage run flood_forecast/trainer.py -p tests/decoder_test.json
            echo -e 'running trainer_custom_encode \n'
            coverage run flood_forecast/trainer.py -p tests/custom_encode.json
      - run: 
          name: upload results
          when: always
          command: bash <(curl -s https://codecov.io/bash) -cF python
      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results-trainer

  plot_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - restore_cache:  # ensure this step occurs *before* installing dependencies
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            sudo pip install pipenv
            sudo pip install coverage
            sudo pip install --upgrade --force-reinstall --quiet -r requirements.txt
            sudo python setup.py develop --no-deps

      - save_cache:
          key: requirements-v2-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - ~/.local

      - run:
          name: plot tests
          when: always
          command: |
            coverage run -m unittest -v tests/test_plot.py
            coverage run -m unittest -v tests/test_explain_model_output.py
      - run:
          name: upload_stuff
          when: always
          command: bash <(curl -s https://codecov.io/bash) -cF python

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: test-results
          destination: test-results-plot


workflows:
  version: 2

  test_and_build:
    jobs:
      - setup_and_install
      - linting:
          requires:
            - setup_and_install
      - evaluator_test:
          requires:
            - linting
      - data_quality_test:
          requires:
            - linting
      - model_basic_test:
          requires:
            - linting
      - decoder_test:
          requires:
            - linting
      - trainer_test:
          requires:
            - linting
      - plot_test:
          requires:
            - linting
